config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resources :messages
  end
  devise_for :users
  root to: 'rooms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  after_commit { broadcast_append_to "room_#{room.id}" }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    @message = current_user.messages.build(message_params)
    @message.room_id = params[:room_id]
    @message.save
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    @messages = @room.messages
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/controllers/turbo_controller.rb
class TurboController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
          rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html,
            status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <%= link_to "Home", root_path, class: "navbar-brand font-semibold text-xl tracking-tight" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <% if user_signed_in? %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        <% end %>
      </li>
      <li class="nav-item">
        <span class="nav-link">Hello there <%= current_user ? current_user.email : "friend" %></span>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuickChat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for([@room, Message.new], data: {
    action: "turbo:submit-end->messages#resetForm",
    messages_target: "input_form"
  }) do |f| %>
  <div class="form-group">
    <%= f.input :body, label: false,
        input_html: { placeholder: "Type a message" },
        wrapper_html: { class: "form-control" },
        class: "form-control"
    %>
    <%= f.submit "Send", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<%= turbo_frame_tag(dom_id(message)) do %>
  <div class="row">
    <%= "#{message.user.email}: #{message.body}" %>
  </div>
<% end %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/rooms/_form.html.erb
<%= simple_form_for(@room) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>" data-controller="messages">
  <%= turbo_stream_from dom_id(room) %>
  <h1><%= room.name %></h1>
  <div id="messages" data-messages-target="container">
    <% @messages&.each do |message| %>
      <%= render 'messages/message', message: message %>
    <% end %>
  </div>
  <%= render 'messages/form', room: room %>
</div>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Show this room", @room %> |
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rooms</h1>

<div id="rooms">
  <% @rooms.each do |room| %>
    <%= link_to room.name.capitalize, room %>
    <br/>
  <% end %>
</div>

<%= link_to "New room", new_room_path %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @room %>

<div>
  <%= link_to "Edit this room", edit_room_path(@room) %> |
  <%= link_to "Back to rooms", rooms_path %>

  <%= button_to "Destroy this room", @room, method: :delete %>
</div>